### ISSUE TITLE
[FE] 온보딩 화면 - 2 (레파지토리 선택)

### ISSUE THREAD

**Issue by speardragon** [KTB-Sixmen/gitfolio_front#11]
### Description
온보딩 두 번째 화면인 레파지토리 선택 화면을 구현한다. 강조할 포인트를 같이 입력 받아 전송하는 기능이 있어야 한다.

### TODO
- [ ] 사용자의 레파지토리를 가져오는 API 요청
- [ ] 가져온 레파지토리를 배치하는 화면 구현
- [ ] 강조할 포인트를 입력 받는 form 배치
- [ ] 전송 버튼(백엔드로 이력서 생성 요청과 프론트에서는 /home 으로 리디렉션 된다.)

### ETC (관련 자료 및 링크, 사진 등)
