### ISSUE TITLE
[Refactor] 중간 평가 전 점검 이슈

### ISSUE THREAD

**Issue by speardragon** [KTB-Sixmen/gitfolio_front#51]
### Description
중간 평가 전 자잘한 수정 및 리팩토링을 진행해야 합니다.

### TODO
- [x]  이력서 생성 이후 토스트 UI에서 버튼을 누르면 만들어진 이력서로 넘어가지도록(현재는 내 이력서 화면으로 넘어가고 있음)
- [x]  종아요를 누른 이력서 버기 버튼 준비 중입니다 처리하기
- [x]  내 댓글만 삭제하도록 수정
- [x]  내 이력서 화면 날짜 하드코딩들 바꾸기
- [x]  이력서 수정 UI에서 드래그한 텍스트를 x 버튼을 눌렀을 때 제거되도록 하기
- [x] 좋아요 안되는 문제
- [x] 헤더에 알림 컴포넌트 추가하기(기능은 나중에)
