### ISSUE TITLE
[Feature] 이력서를 AI와 수정할 수 있다.

### ISSUE THREAD

**Issue by speardragon** [KTB-Sixmen/gitfolio_front#76]
### Description
AI와의 클라이언트 사이의 인터랙션을 제공하여 이력서 수정 기능을 제공할 수 있도록 한다.

### TODO
- [ ] 텍스트 드래그 기능
- [ ] 채팅 전송 기능
- [ ] 이력서 수정 동안 보여줄 UI
